/* tslint:disable */
/**
 * flow-protocol-model-common
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { BigNumberT } from "@imtbl/imx-sdk"
import * as runtime from "./runtime"

export interface GetEthBalanceRequest {
	address: string;
}

export interface GetErc20BalanceRequest {
	address: string;
	contractAddress: string
}

export interface GetAllBalancesRequest {
	ownerAddress: string;
}

export interface GetAllBalancesResponse {
	"result": {
		"symbol": string,
		"balance": BigNumberT,
		"preparing_withdrawal": string,
		"withdrawable": string
	}[],
	"cursor": string
}


export class ImxBalanceControllerApi extends runtime.BaseAPI {

	async getAllBalancesRaw(
		requestParameters: GetAllBalancesRequest,
	): Promise<runtime.ApiResponse<GetAllBalancesResponse>> {
		if (requestParameters.ownerAddress === null || requestParameters.ownerAddress === undefined) {
			throw new runtime.RequiredError("ownerAddress", "Required parameter requestParameters.ownerAddress was null or undefined when calling getAllBalances.")
		}

		const queryParameters: runtime.HTTPQuery = {}

		const headerParameters: runtime.HTTPHeaders = {}

		const response = await this.request({
			path: "/balances/{address}".replace(`{${"address"}}`, encodeURIComponent(String(requestParameters.ownerAddress))),
			method: "GET",
			headers: headerParameters,
			query: queryParameters,
		})
		// @ts-ignore
		return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue as GetAllBalancesResponse)

	}

	/**
	 */
	async getAllBalances(requestParameters: GetAllBalancesRequest): Promise<GetAllBalancesResponse> {
		const response = await this.getAllBalancesRaw(requestParameters)
		return await response.value()
	}
}
